### ISSUE TITLE
Wrong CPU and Prysm TCP Port output 

### ISSUE THREAD

**Issue by Jor-Tech** [pondron/valid8r#14]
First of all, amazing tool you're working on, would like to see it standard packed into all eth2 validator clients.

See my issue described down here.

Have my validator running smooth with geth and prysm on mainnet.

Running `valid8tor --eth1 geth --eth2 prysm` gives me this output:

System Requirements:
Time Sync - NTP Tue Mar 16 21:29:58 2021 vs LOCAL 21:29:58.200544041
✅ OS Version up-to-date with LTS:
         Requirement "20.04" => Have ("ubuntu" "20.04")
✅ Memory requirement reached:
         Preferred 16GB(min 8GB) => Have 16336372 KB
❌ Processor count requirement NOT reached:
         Preferred 4 CPU(s)(min 2) => Have 4 CPU(s)
✅ Disk size requirement reached:
         Preffered 1TB(min 300GB) => Have 1967396192256 bytes

Network Requirements:
✅ GETH is listening on port: 30303
✅ GETH is listening on port: 8545
❌ PRYSM IS NOT LISTENING ON PORT: 13000
✅ No default ssh agent running on port: 22

ETH1 Client Check: GETH
✅ GETH(Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16) is the latest release: "v1.10.1"
✅ GETH is on mainnet
✅ Valid8r can reach Infura at latest block: 12051863(verify at https://etherscan.io/blocks)
✅ GETH is in sync, latest block: 12051863(verify at https://etherscan.io/blocks)
✅ GETH currently has 50 peers

From which I think;

**1. The CPU-check output isn't correctly**
"_Processor count requirement NOT reached_" but "_=> Have 4 CPU(s)_" which is the preferred count.
The CPU in my system is an Intel® Core™ i5-4690K: [link](https://ark.intel.com/content/www/us/en/ark/products/80811/intel-core-i5-4690k-processor-6m-cache-up-to-3-90-ghz.html)

**2. The Prysm TCP port-check output isn't correctly**
Running defaults (tcp 13000 and udp 12000), without flags to change ports.
Ports are allowed in ufw and forwarded in router.
Still getting output _"PRYSM IS NOT LISTENING ON PORT: 13000"_

Wondering why it doesn't pass those two as it looks like I've set it up right.

**Comment by tclukies** [comment]
Thanks for the kind words. We are pretty excited about the project as well. We are certainly still in active development, so your feedback is helpful. 

1. Missed a >= in the logic when computing that output. This will be addressed in the next release. 
2. Eth2 requirements should be updated as part of our next release as well. From current testing, I think you are still seeing the output as "not listening" because Prysm uses your private ip instead of 127.0.0.1. We plan on adjusting for this in the next release . As part of our next release, we will likely not have flags for custom ports and cover the defaults for each client only. Custom parts will be included in a future release.

**Comment by Jor-Tech** [comment]
Thanks for the feedback.

Looking forward to the future releases and will keep on testing.

**Comment by tclukies** [comment]
This issue has been addressed in release 1.0.0, please let us know if you seen any other problems!
